name: 'Terraform Setup'
description: 'Checkout caller repository, setup Terraform, and configure environment variables'

inputs:
  terraform-version:
    description: 'Terraform version to install'
    required: false
    type: string
    default: '1.7.0'

outputs:
  terraform-version:
    description: 'Installed Terraform version'
    value: ${{ steps.verify.outputs.terraform-version }}

runs:
  using: composite
  steps:
    - name: Checkout caller repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0
        persist-credentials: false
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      with:
        terraform_version: ${{ inputs.terraform-version }}
    
    - name: Verify Terraform installation
      id: verify
      shell: bash
      run: |
        echo "::group::Terraform Version"
        terraform version
        echo "terraform-version=$(terraform version -json | jq -r '.terraform_version')" >> $GITHUB_OUTPUT
        echo "::endgroup::"
    
    - name: Configure Terraform environment
      shell: bash
      run: |
        echo "TF_IN_AUTOMATION=true" >> $GITHUB_ENV
        echo "TF_INPUT=false" >> $GITHUB_ENV
        echo "TF_CLI_ARGS=-no-color" >> $GITHUB_ENV
    
    - name: Setup summary
      shell: bash
      run: |
        echo "::group::Common Setup Complete"
        echo "✅ Caller repository checked out"
        echo "✅ Terraform $(terraform version -json | jq -r '.terraform_version') installed"
        echo "✅ Environment variables configured:"
        echo "   - TF_IN_AUTOMATION=true"
        echo "   - TF_INPUT=false"
        echo "   - TF_CLI_ARGS=-no-color"
        echo "::endgroup::"
